/* lsm9ds1.h - header file for LSM9DS1 accelerometer and gyroscope sensor driver
 */

/*
 * Copyright (c) 2024 J.R. Versteegh
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_SENSOR_LSM9DS1_LSMDS1_H_
#define ZEPHYR_DRIVERS_SENSOR_LSM9DS1_LSMDS1_H_

#include <zephyr/drivers/gpio.h>
#include <zephyr/drivers/i2c.h>
#include <zephyr/sys/util.h>
#include <zephyr/types.h>

#define LSM9DS1_REG_WHO_AM_I 0x0F
#define LSM9DS1_VAL_WHO_AM_I 0x68

#define LSM9DS1_REG_INT1_CTRL 0x0C
#define LSM9DS1_REG_INT2_CTRL 0x0D

#define LSM9DS1_REG_CTRL_REG1 0x10
#define LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT 5
#define LSM9DS1_REG_CTRL_REG1_ODR_G_MASK                                       \
  (7 << LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT)
#define LSM9DS1_REG_CTRL_REG1_FS_G_SHIFT 3
#define LSM9DS1_REG_CTRL_REG1_FS_G_MASK (3 << LSM9DS1_REG_CTRL_REG1_FS_G_SHIFT)
#define LSM9DS1_REG_CTRL_REG1_BW_G_SHIFT 0
#define LSM9DS1_REG_CTRL_REG1_BW_G_MASK (3 << LSM9DS1_REG_CTRL_REG1_BW_G_SHIFT)

#ifndef CONFIG_LSM9DS1_GYRO_ENABLE
#define LSM9DS1_DEFAULT_ODR_G (0 << LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_SAMPLING_RATE_14_9)
#define LSM9DS1_DEFAULT_ODR_G (1 << LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT
#elif defined(CONFIG_LSM9DS1_GYRO_SAMPLING_RATE_59_5)
#define LSM9DS1_DEFAULT_ODR_G (2 << LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT
#elif defined(CONFIG_LSM9DS1_GYRO_SAMPLING_RATE_119)
#define LSM9DS1_DEFAULT_ODR_G (3 << LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT
#elif defined(CONFIG_LSM9DS1_GYRO_SAMPLING_RATE_238)
#define LSM9DS1_DEFAULT_ODR_G (4 << LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT
#elif defined(CONFIG_LSM9DS1_GYRO_SAMPLING_RATE_476)
#define LSM9DS1_DEFAULT_ODR_G (5 << LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT
#elif defined(CONFIG_LSM9DS1_GYRO_SAMPLING_RATE_952)
#define LSM9DS1_DEFAULT_ODR_G (6 << LSM9DS1_REG_CTRL_REG1_ODR_G_SHIFT
#else
#error "No gyroscope sampling frequency set"
#endif

#if defined(CONFIG_LSM9DS1_GYRO_FULL_SCALE_245)
#define LSM9DS1_DEFAULT_FS_G (0 << LSM9DS1_REG_CTRL_REG1_FS_G_SHIFT)
#elif define(CONFIG_LSM9DS1_GYRO_FULL_SCALE_500)
#define LSM9DS1_DEFAULT_FS_G (1 << LSM9DS1_REG_CTRL_REG1_FS_G_SHIFT)
#elif define(CONFIG_LSM9DS1_ACCEL_FULL_SCALE_2000)
#define LSM9DS1_DEFAULT_FS_G (3 << LSM9DS1_REG_CTRL_REG1_FS_G_SHIFT)
#else
#error "No gyroscope scale set"
#endif

#if defined(CONFIG_LSM9DS1_GYRO_BW_FILTER_LOW)
#define LSM9DS1_DEFAULT_BW_G (0 << LSM9DS1_REG_CTRL_REG1_BW_G_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_BW_FILTER_MID_LOW)
#define LSM9DS1_DEFAULT_BW_G (1 << LSM9DS1_REG_CTRL_REG1_BW_G_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_BW_FILTER_MID_HIGH)
#define LSM9DS1_DEFAULT_BW_G (2 << LSM9DS1_REG_CTRL_REG1_BW_G_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_BW_FILTER_HIGH)
#define LSM9DS1_DEFAULT_BW_G (3 << LSM9DS1_REG_CTRL_REG1_BW_G_SHIFT)
#else
#define LSM9DS1_DEFAULT_BW_G 0
#endif

#define LSM9DS1_REG_CTRL_REG2 0x11
#define LSM9DS1_REG_CTRL_REG2_INT_SEL_SHIFT 2
#define LSM9DS1_REG_CTRL_REG2_INT_SEL_MASK                                     \
  (3 << LSM9DS1_REG_CTRL_REG2_INT_SEL_SHIFT)
#define LSM9DS1_REG_CTRL_REG2_OUT_SEL_SHIFT 0
#define LSM9DS1_REG_CTRL_REG2_OUT_SEL_MASK                                     \
  (3 << LSM9DS1_REG_CTRL_REG2_OUT_SEL_SHIFT)

#if defined(CONFIG_LSM9DS1_GYRO_SECOND_LPF_ENABLE)
#define LSM9DS1_DEFAULT_OUT_SEL (2 << LSM9DS1_REG_CTRL_REG2_OUT_SEL_SHIFT)
#else
#define LSM9DS1_DEFAULT_OUT_SEL (0 << LSM9DS1_REG_CTRL_REG2_OUT_SEL_SHIFT)
#endif

#define LSM9DS1_REG_CTRL_REG3 0x12
#define LSM9DS1_REG_CTRL_REG3_LP_MODE_SHIFT 7
#define LSM9DS1_REG_CTRL_REG3_LP_MODE_MASK                                     \
  (1 << LSM9DS1_REG_CTRL_REG3_LP_MODE_SHIFT)
#define LSM9DS1_REG_CTRL_REG3_HPF_EN_SHIFT 6
#define LSM9DS1_REG_CTRL_REG3_HPF_EN_MASK                                      \
  (1 << LSM9DS1_REG_CTRL_REG3_HPF_EN_SHIFT)
#define LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT 0
#define LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_MASK                                  \
  (15 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)

#if defined(CONFIG_LSM9DS1_GYRO_HPF_ENABLE)
#define LSM9DS1_DEFAULT_HPF_ENABLE (1 << LSM9DS1_REG_CTRL_REG3_HPF_EN_SHIFT)
#else
#define LSM9DS1_DEFAULT_HPF_ENABLE (0 << LSM9DS1_REG_CTRL_REG3_HPF_EN_SHIFT)
#endif

#if defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_15
#define LSM9DS1_DEFAULT_HPF_CUTOFF (0 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_30
#define LSM9DS1_DEFAULT_HPF_CUTOFF (1 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_60
#define LSM9DS1_DEFAULT_HPF_CUTOFF (2 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_150
#define LSM9DS1_DEFAULT_HPF_CUTOFF (3 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_250
#define LSM9DS1_DEFAULT_HPF_CUTOFF (4 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_500
#define LSM9DS1_DEFAULT_HPF_CUTOFF (5 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_1000
#define LSM9DS1_DEFAULT_HPF_CUTOFF (6 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_2500
#define LSM9DS1_DEFAULT_HPF_CUTOFF (7 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_5000
#define LSM9DS1_DEFAULT_HPF_CUTOFF (8 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#elif defined(CONFIG_LSM9DS1_GYRO_HDF_ODR_DIV_10000
#define LSM9DS1_DEFAULT_HPF_CUTOFF (9 << LSM9DS1_REG_CTRL_REG3_HPF_CUTOFF_SHIFT)
#else
#define LSM9DS1_DEFAULT_HPF_CUTOFF 0
#endif

#define LSM9DS1_REG_ORIENT_CFG 0x13
#define LSM9DS1_REG_ORIENT_CFG_SIGN_X_SHIFT 5
#define LSM9DS1_REG_ORIENT_CFG_SIGN_X_MASK                                     \
  (1 << LSM9DS1_REG_ORIENT_CFG_SIGN_X_SHIFT)
#define LSM9DS1_REG_ORIENT_CFG_SIGN_Y_SHIFT 4
#define LSM9DS1_REG_ORIENT_CFG_SIGN_Y_MASK                                     \
  (1 << LSM9DS1_REG_ORIENT_CFG_SIGN_Y_SHIFT)
#define LSM9DS1_REG_ORIENT_CFG_SIGN_Z_SHIFT 3
#define LSM9DS1_REG_ORIENT_CFG_SIGN_Z_MASK                                     \
  (1 << LSM9DS1_REG_ORIENT_CFG_SIGN_Z_SHIFT)
#define LSM9DS1_REG_ORIENT_CFG_ORIENT_SHIFT 0
#define LSM9DS1_REG_ORIENT_CFG_ORIENT_MASK                                     \
  (1 << LSM9DS1_REG_ORIENT_CFG_ORIENT_SHIFT)

#define LSM9DS1_REG_INT_GEN_SRC 0x14

#define LSM9DS1_REG_OUT_TEMP_L 0x15
#define LSM9DS1_REG_OUT_TEMP_H 0x16

#define LSM9DS1_REG_STATUS_REG 0x17

#define LSM9DS1_REG_OUT_X_L_G 0x18
#define LSM9DS1_REG_OUT_X_H_G 0x19
#define LSM9DS1_REG_OUT_Y_L_G 0x1A
#define LSM9DS1_REG_OUT_Y_H_G 0x1B
#define LSM9DS1_REG_OUT_Z_L_G 0x1C
#define LSM9DS1_REG_OUT_Z_H_G 0x1D

#define LSM9DS1_REG_CTRL_REG4 0x1E
#define LSM9DS1_REG_CTRL_REG5 0x1F

#define LSM9DS1_REG_CTRL_REG6 0x20
#define LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT 5
#define LSM9DS1_REG_CTRL_REG6_ODR_XL_MASK                                      \
  (7 << LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT)
#define LSM9DS1_REG_CTRL_REG6_FS_XL_SHIFT 3
#define LSM9DS1_REG_CTRL_REG6_FS_XL_MASK                                       \
  (3 << LSM9DS1_REG_CTRL_REG6_FS_XL_SHIFT)
#define LSM9DS1_REG_CTRL_REG6_BW_SCAL_ODR_SHIFT 2
#define LSM9DS1_REG_CTRL_REG6_BW_SCAL_ODR_MASK                                 \
  (1 << LSM9DS1_REG_CTRL_REG6_BW_SCAL_ODR_SHIFT)
#define LSM9DS1_REG_CTRL_REG6_BW_XL_SHIFT 0
#define LSM9DS1_REG_CTRL_REG6_BW_XL_MASK                                       \
  (3 << LSM9DS1_REG_CTRL_REG6_BW_XL_SHIFT)

#ifndef CONFIG_LSM9DS1_ACCEL_ENABLE
#define LSM9DS1_DEFAULT_ODR_XL (0 << LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT)
#elif defined(CONFIG_LSM9DS1_ACCEL_SAMPLING_RATE_10)
#define LSM9DS1_DEFAULT_ODR_XL (1 << LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT)
#elif defined(CONFIG_LSM9DS1_ACCEL_SAMPLING_RATE_50)
#define LSM9DS1_DEFAULT_ODR_XL (2 << LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT)
#elif defined(CONFIG_LSM9DS1_ACCEL_SAMPLING_RATE_119)
#define LSM9DS1_DEFAULT_ODR_XL (3 << LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT)
#elif defined(CONFIG_LSM9DS1_ACCEL_SAMPLING_RATE_238)
#define LSM9DS1_DEFAULT_ODR_XL (4 << LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT)
#elif defined(CONFIG_LSM9DS1_ACCEL_SAMPLING_RATE_476)
#define LSM9DS1_DEFAULT_ODR_XL (5 << LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT)
#elif defined(CONFIG_LSM9DS1_ACCEL_SAMPLING_RATE_952)
#define LSM9DS1_DEFAULT_ODR_XL (6 << LSM9DS1_REG_CTRL_REG6_ODR_XL_SHIFT)
#else
#error "No acceleration sampling frequency set"
#endif

#if defined(CONFIG_LSM9DS1_ACCEL_FULL_SCALE_2)
#define LSM9DS1_DEFAULT_FS_XL (0 << LSM9DS1_REG_CTRL_REG6_FS_XL_SHIFT)
#elif define(CONFIG_LSM9DS1_ACCEL_FULL_SCALE_4)
#define LSM9DS1_DEFAULT_FS_XL (2 << LSM9DS1_REG_CTRL_REG6_FS_XL_SHIFT)
#elif define(CONFIG_LSM9DS1_ACCEL_FULL_SCALE_8)
#define LSM9DS1_DEFAULT_FS_XL (3 << LSM9DS1_REG_CTRL_REG6_FS_XL_SHIFT)
#elif define(CONFIG_LSM9DS1_ACCEL_FULL_SCALE_16)
#define LSM9DS1_DEFAULT_FS_XL (1 << LSM9DS1_REG_CTRL_REG6_FS_XL_SHIFT)
#else
#error "No acceleration scale set"
#endif

#if defined(CONFIG_LSM9DS1_ACCEL_ENABLE_BW_SETTING)
#define LSM9DS1_DEFAULT_BW_FILTER_ENABLE 1
#else
#define LSM9DS1_DEFAULT_BW_FILTER_ENABLE 0
#define LSM9DS1_DEFAULT_BW_FILTER_SETTING 0
#endif

#if defined(LSM9DS1_ACCEL_BW_FILTER_408)
#define LSM9DS1_DEFAULT_BW_FILTER_SETTING                                      \
  (0 << LSM9DS1_REG_CTRL_REG6_BW_XL_SHIFT)
#elif defined(LSM9DS1_ACCEL_BW_FILTER_211)
#define LSM9DS1_DEFAULT_BW_FILTER_SETTING                                      \
  (1 << LSM9DS1_REG_CTRL_REG6_BW_XL_SHIFT)
#elif defined(LSM9DS1_ACCEL_BW_FILTER_105)
#define LSM9DS1_DEFAULT_BW_FILTER_SETTING                                      \
  (2 << LSM9DS1_REG_CTRL_REG6_BW_XL_SHIFT)
#elif defined(LSM9DS1_ACCEL_BW_FILTER_50)
#define LSM9DS1_DEFAULT_BW_FILTER_SETTING                                      \
  (3 << LSM9DS1_REG_CTRL_REG6_BW_XL_SHIFT)
#endif

#define LSM9DS1_REG_CTRL_REG7 0x21
#define LSM9DS1_REG_CTRL_REG7_HR_SHIFT 7
#define LSM9DS1_REG_CTRL_REG7_HR_MASK (1 << LSM9DS1_REG_CTRL_REG7_HR_SHIFT)
#define LSM9DS1_REG_CTRL_REG7_DCF_SHIFT 5
#define LSM9DS1_REG_CTRL_REG7_DCF_MASK (3 << LSM9DS1_REG_CTRL_REG7_DCF_SHIFT)
#define LSM9DS1_REG_CTRL_REG7_FDS_SHIFT 2
#define LSM9DS1_REG_CTRL_REG7_FDS_MASK (1 << LSM9DS1_REG_CTRL_REG7_FDS_SHIFT)

#define LSM9DS1_REG_CTRL_REG8 0x22
#define LSM9DS1_REG_CTRL_REG9 0x23
#define LSM9DS1_REG_CTRL_REG10 0x24

#define LSM9DS1_REG_INT_GEN_SRC_XL 0x26
#define LSM9DS1_REG_STATUS_REG_XL 0x27

#define LSM9DS1_REG_OUT_X_L_XL 0x28
#define LSM9DS1_REG_OUT_X_H_XL 0x29
#define LSM9DS1_REG_OUT_Y_L_XL 0x2A
#define LSM9DS1_REG_OUT_Y_H_XL 0x2B
#define LSM9DS1_REG_OUT_Z_L_XL 0x2C
#define LSM9DS1_REG_OUT_Z_H_XL 0x2D

struct lsm9ds1_config {
  struct i2c_dt_spec i2c;

#if !defined(CONFIG_LSM9DS1_TRIGGER_NONE)
  struct gpio_dt_spec int_gpio;
#endif
};

struct lsm9ds1_data {
#if defined(CONFIG_LSM9DS1_TRIGGERS)
  struct k_sem sem;
#endif

#if !defined(CONFIG_LSM9DS1_TRIGGER_OWN_THREAD)
  K_KERNEL_STACK_MEMBER(thread_stack, CONFIG_LSM9DS1_THREAD_STACK_SIZE);
  struct k_thread thread;
  const struct device *dev;

  struct gpio_callback gpio_cb;
  const struct sensor_trigger *trigger_drdy;
  sensor_trigger_handler_t handler_drdy;
#endif

  int accel_x, accel_y, accel_z;
  int gyro_x, gyro_y, gyro_z;
  int temp;
#if defined(CONFIG_LSM9DS1_SET_RUNTIME)
  uint8_t accel_fs;
  uint8_t gyro_fs;
#endif
};

#if !defined(CONFIG_LSM9DS1_TRIGGER_NONE)
int lsm9ds1_trigger_set(const struct device *dev,
                        const struct sensor_trigger *trig,
                        sensor_trigger_handler_t handler);

int lsm9ds1_init_interrupt(const struct device *dev);
#endif

#endif /* ZEPHYR_DRIVERS_SENSOR_lsm9ds1_LSMDS1_H_ */
