/* sensor_lsm9ds1_magn.h - header file for LSM9DS1 magnetometer
 * sensor driver
 */

#ifndef ZEPHYR_DRIVERS_SENSOR_LSM9DS1_MAGN_LSM9DS1_MAGN_H_
#define ZEPHYR_DRIVERS_SENSOR_LSM9DS1_MAGN_LSM9DS1_MAGN_H_

#include <zephyr/drivers/i2c.h>
#include <zephyr/sys/util.h>
#include <zephyr/types.h>

#define LSM9DS1_MAGN_REG_OFFSET_X_L 0x05
#define LSM9DS1_MAGN_REG_OFFSET_X_H 0x06
#define LSM9DS1_MAGN_REG_OFFSET_Y_L 0x07
#define LSM9DS1_MAGN_REG_OFFSET_Y_H 0x08
#define LSM9DS1_MAGN_REG_OFFSET_Z_L 0x09
#define LSM9DS1_MAGN_REG_OFFSET_Z_H 0x0A

#define LSM9DS1_MAGN_REG_WHO_AM_I 0x0F
#define LSM9DS1_MAGN_VAL_WHO_AM_I 0x3D

#define LSM9DS1_MAGN_REG_CTRL_REG1 0x20
#define LSM9DS1_MAGN_REG_CTRL_REG1_TEMP_COMP_SHIFT 7
#define LSM9DS1_MAGN_REG_CTRL_REG1_TEMP_COMP_MASK                              \
  (1 << LSM9DS1_MAGN_REG_CTRL_REG1_TEMP_COMP_SHIFT)
#define LSM9DS1_MAGN_REG_CTRL_REG1_XY_OPR_SHIFT 5
#define LSM9DS1_MAGN_REG_CTRL_REG1_XY_OPR_MASK                                 \
  (3 << LSM9DS1_MAGN_REG_CTRL_REG1_XY_OPR_SHIFT)
#define LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT 2
#define LSM9DS1_MAGN_REG_CTRL_REG1_ODR_MASK                                    \
  (7 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)

#define LSM9DS1_MAGN_REG_CTRL_REG2 0x21
#define LSM9DS1_MAGN_REG_CTRL_REG2_FS_SHIFT 5
#define LSM9DS1_MAGN_REG_CTRL_REG2_FS_MASK                                     \
  (3 << LSM9DS1_MAGN_REG_CTRL_REG2_FS_SHIFT)

#define LSM9DS1_MAGN_REG_CTRL_REG3 0x22

#define LSM9DS1_MAGN_REG_CTRL_REG4 0x23
#define LSM9DS1_MAGN_REG_CTRL_REG4_Z_OPR_SHIFT 2
#define LSM9DS1_MAGN_REG_CTRL_REG4_Z_OPR_MASK                                  \
  (3 << LSM9DS1_MAGN_REG_CTRL_REG4_Z_OPR_SHIFT)

#define LSM9DS1_MAGN_REG_CTRL_REG5 0x24

#if defined(CONFIG_LSM9DS1_MAGN_TEMP_COMP)
#define LSM9DS1_MAGN_DEFAULT_TEMP_COMP                                         \
  (1 << LSM9DS1_MAGN_REG_CTRL_REG1_TEMP_COMP_SHIFT)
#else
#define LSM9DS1_MAGN_DEFAULT_TEMP_COMP                                         \
  (0 << LSM9DS1_MAGN_REG_CTRL_REG1_TEMP_COMP_SHIFT)
#endif

#if defined(CONFIG_LSM9DS1_MAGN_LOW_POWER)
#define LSM9DS1_MAGN_DEFAULT_XY_OPR                                            \
  (0 << LSM9DS1_MAGN_REG_CTRL_REG1_XY_OPR_SHIFT)
#define LSM9DS1_MAGN_DEFAULT_Z_OPR (0 << LSM9DS1_MAGN_REG_CTRL_REG4_Z_OPR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_MED_PERF)
#define LSM9DS1_MAGN_DEFAULT_XY_OPR                                            \
  (1 << LSM9DS1_MAGN_REG_CTRL_REG1_XY_OPR_SHIFT)
#define LSM9DS1_MAGN_DEFAULT_Z_OPR (1 << LSM9DS1_MAGN_REG_CTRL_REG4_Z_OPR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_HIGH_PERF)
#define LSM9DS1_MAGN_DEFAULT_XY_OPR                                            \
  (2 << LSM9DS1_MAGN_REG_CTRL_REG1_XY_OPR_SHIFT)
#define LSM9DS1_MAGN_DEFAULT_Z_OPR (2 << LSM9DS1_MAGN_REG_CTRL_REG4_Z_OPR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_ULTRA_PERF)
#define LSM9DS1_MAGN_DEFAULT_XY_OPR                                            \
  (3 << LSM9DS1_MAGN_REG_CTRL_REG1_XY_OPR_SHIFT)
#define LSM9DS1_MAGN_DEFAULT_Z_OPR (3 << LSM9DS1_MAGN_REG_CTRL_REG4_Z_OPR_SHIFT)
#else
#error "No power mode selected"
#endif

#if defined(CONFIG_LSM9DS1_MAGN_SAMPLING_RATE_0_625)
#define LSM9DS1_MAGN_DEFAULT_ODR (0 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_SAMPLING_RATE_1_25)
#define LSM9DS1_MAGN_DEFAULT_ODR (1 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_SAMPLING_RATE_2_5)
#define LSM9DS1_MAGN_DEFAULT_ODR (2 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_SAMPLING_RATE_5)
#define LSM9DS1_MAGN_DEFAULT_ODR (3 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_SAMPLING_RATE_10)
#define LSM9DS1_MAGN_DEFAULT_ODR (4 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_SAMPLING_RATE_20)
#define LSM9DS1_MAGN_DEFAULT_ODR (5 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_SAMPLING_RATE_40)
#define LSM9DS1_MAGN_DEFAULT_ODR (6 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_SAMPLING_RATE_80)
#define LSM9DS1_MAGN_DEFAULT_ODR (7 << LSM9DS1_MAGN_REG_CTRL_REG1_ODR_SHIFT)
#else
#error "No sampling/output data rate selected"
#endif

#if defined(CONFIG_LSM9DS1_MAGN_FULL_SCALE_4)
#define LSM9DS1_MAGN_DEFAULT_FS (0 << LSM9DS1_MAGN_REG_CTRL_REG2_FS_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_FULL_SCALE_8)
#define LSM9DS1_MAGN_DEFAULT_FS (1 << LSM9DS1_MAGN_REG_CTRL_REG2_FS_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_FULL_SCALE_12)
#define LSM9DS1_MAGN_DEFAULT_FS (2 << LSM9DS1_MAGN_REG_CTRL_REG2_FS_SHIFT)
#elif defined(CONFIG_LSM9DS1_MAGN_FULL_SCALE_16)
#define LSM9DS1_MAGN_DEFAULT_FS (3 << LSM9DS1_MAGN_REG_CTRL_REG2_FS_SHIFT)
#else
#error "No full scale selected"
#endif

#define LSM9DS1_MAGN_REG_OUT_X_L 0x28
#define LSM9DS1_MAGN_REG_OUT_X_H 0x29
#define LSM9DS1_MAGN_REG_OUT_Y_L 0x2A
#define LSM9DS1_MAGN_REG_OUT_Y_H 0x2B
#define LSM9DS1_MAGN_REG_OUT_Z_L 0x2C
#define LSM9DS1_MAGN_REG_OUT_Z_H 0x2D

struct lsm9ds1_magn_config {
  struct i2c_dt_spec i2c;
};

struct lsm9ds1_magn_sample {
  int16_t x;
  int16_t y;
  int16_t z;
};

struct lsm9ds1_magn_data {
  union {
    int16_t vec[3];
    struct lsm9ds1_magn_sample sample;
  };
  uint8_t fs;
};

#endif /* ZEPHYR_DRIVERS_SENSOR_LSM9DS1_MAGN_LSM9DS1_MAGN_H_ */
